version: '3.8'

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - fountcore_net
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - fountcore_net
  core_orm:
    build: .
    restart: always
    command: uvicorn config.asgi:application --reload --host 0.0.0.0 --port 8001
    volumes:
    - .:/app
    - static_volume:/app/static
    ports:
      - 8001:8001
    env_file:
      - .env.dev
    depends_on:
      - db
      - rabbitmq
    networks:
      - fountcore_net
  db:
    image: postgres:13.0-alpine
    # ports:
      # - 543:543
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=lex3man
      - POSTGRES_PASSWORD=Django_admin192168
      - POSTGRES_DB=fountcore_main
    networks:
      - fountcore_net

volumes:
  postgres_data:
  static_volume:

networks:
  fountcore_net:
    driver: bridge
