# Generated by Django 4.1.2 on 2022-10-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=11, unique=True, verbose_name='ID пользователя')),
                ('name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('status', models.CharField(choices=[('usr', 'Пользователь'), ('stf', 'Персонал'), ('adm', 'Администратор'), ('own', 'Владыка')], default='usr', max_length=3, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['uid', 'name'],
            },
        ),
    ]
