# Generated by Django 4.1.2 on 2022-10-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_bot_bot_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=20, verbose_name='ID')),
                ('username', models.CharField(max_length=150, null=True, verbose_name='Имя пользователя')),
                ('fname', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('lname', models.CharField(max_length=150, null=True, verbose_name='Фамилия')),
                ('on_fox', models.BooleanField(default=True, verbose_name='Слушает')),
                ('from_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.bot', verbose_name='Через бота')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.telegramasset', verbose_name='Телеграм'),
        ),
    ]
