# Generated by Django 4.1.2 on 2022-10-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_state_name_telegramasset_state_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramasset',
            name='state_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Стадия'),
        ),
    ]
