# Generated by Django 4.1.2 on 2022-10-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site', verbose_name='Сайт'),
        ),
    ]
