# Generated by Django 4.1.2 on 2022-10-16 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_item_identity_alter_site_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='IslandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(default='item_000', max_length=50, unique=True, verbose_name='Идентификатор')),
                ('caption', models.CharField(max_length=100, verbose_name='Наименование')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.site', verbose_name='Сайт')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.islandtype', verbose_name='Тип сомпоненты')),
            ],
        ),
    ]
