# Generated by Django 4.1.2 on 2022-10-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_testmodel_island_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='island',
            options={'verbose_name': 'Компонента', 'verbose_name_plural': 'Компоненты'},
        ),
        migrations.AlterModelOptions(
            name='islandtype',
            options={'verbose_name': 'Тип', 'verbose_name_plural': 'Типы'},
        ),
        migrations.RemoveField(
            model_name='island',
            name='site',
        ),
        migrations.AddField(
            model_name='item',
            name='islands',
            field=models.ManyToManyField(to='sites.island', verbose_name='Компоненты'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='island',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.islandtype', verbose_name='Тип компоненты'),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='caption',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
    ]
