# Generated by Django 4.1.2 on 2022-10-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_island_options_alter_islandtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='callback',
            field=models.CharField(max_length=50, null=True, verbose_name='Отклик'),
        ),
    ]
