# Generated by Django 4.1.2 on 2022-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('bot_type', models.CharField(choices=[('TG', 'Telegram bot')], default='TG', max_length=10, verbose_name='Тип бота')),
                ('bot_id', models.CharField(max_length=50, null=True, verbose_name='ID бота')),
                ('active', models.BooleanField(verbose_name='Активен')),
                ('token', models.CharField(max_length=150, verbose_name='Токен')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
            },
        ),
    ]
