# Generated by Django 4.1.2 on 2022-10-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
    ]
