# Generated by Django 4.1.2 on 2022-10-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_button_state_keyboard_contentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='bot_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID бота'),
        ),
    ]
