# Generated by Django 4.1.2 on 2022-10-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_bot_bot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Начало работы'), ('update', 'Изменение')], max_length=10, verbose_name='Тип события')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Дополнительно')),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.bot', verbose_name='Бот')),
            ],
        ),
    ]
