# Generated by Django 4.1.2 on 2022-10-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event_type',
            field=models.CharField(choices=[('start', 'Начало работы'), ('update', 'Изменение'), ('stop', 'Jстановлен')], max_length=10, verbose_name='Тип события'),
        ),
    ]
