# Generated by Django 4.1.2 on 2022-10-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_log_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='event_type',
            field=models.CharField(choices=[('start', 'Начало работы'), ('update', 'Изменение'), ('stop', 'Остановлен')], max_length=10, verbose_name='Тип события'),
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='Команда')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Текст ответа')),
                ('bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.bot', verbose_name='Бот')),
                ('keyboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.keyboard', verbose_name='Клавиатура')),
                ('next_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.command', verbose_name='Следующий блок')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['keyword'],
            },
        ),
    ]
