# Generated by Django 4.1.2 on 2022-10-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_alter_log_event_type_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='callback',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Callback'),
        ),
        migrations.AlterField(
            model_name='button',
            name='row',
            field=models.IntegerField(default=1, verbose_name='Ряд'),
        ),
        migrations.AlterField(
            model_name='command',
            name='keyboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.keyboard', verbose_name='Клавиатура'),
        ),
        migrations.AlterField(
            model_name='command',
            name='next_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.command', verbose_name='Следующий блок'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='from_button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.button', verbose_name='По кнопке'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='keyboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.keyboard', verbose_name='Клавиатура'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='next_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.contentblock', verbose_name='Следующий блок'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.state', verbose_name='Новый стэйт'),
        ),
    ]
