# Generated by Django 4.1.2 on 2022-10-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_alter_button_callback_alter_button_row_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='mode',
            field=models.CharField(choices=[('wfb', 'Ожидание нажатия кнопки'), ('inp', 'Ожидание ввода')], default='wfb', max_length=10, verbose_name='Режим'),
        ),
        migrations.AddField(
            model_name='state',
            name='sid',
            field=models.CharField(default='1', max_length=11, unique=True, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
