# Generated by Django 4.1.2 on 2022-10-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_state_mode_state_sid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={},
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='state',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='next_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='bots.state', verbose_name='Новый стэйт'),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='prev_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previos', to='bots.state', verbose_name='Новый стэйт'),
        ),
        migrations.AlterField(
            model_name='keyboard',
            name='kb_type',
            field=models.CharField(choices=[('std', 'Стандартная'), ('inl', 'Inline')], max_length=10, verbose_name='Тип клавиатуры'),
        ),
    ]
